name: CI

on:
  push:
    branches: [main]
  release:
    types: [published]
  pull_request:

jobs:
  build:
    name: Next.js Build
    env:
      NODE_ENV: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Copy .env
        run: cp .env.example .env